# Generated by Django 4.1 on 2022-12-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
