# Generated by Django 4.1 on 2022-12-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='favorite_authors',
            field=models.ManyToManyField(blank=True, related_name='favorite_author', to='api.author'),
        ),
    ]
