# Generated by Django 4.1 on 2022-11-30 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='authors',
            field=models.ManyToManyField(related_name='authored', to='api.author'),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='characters',
            field=models.ManyToManyField(related_name='appeared', to='api.character'),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='illustrators',
            field=models.ManyToManyField(related_name='illustrated', to='api.illustrator'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.author'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.character'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='illustrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.illustrator'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.publisher'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
