# Generated by Django 4.1 on 2022-11-30 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_authors', models.ManyToManyField(blank=True, null=True, related_name='favorite_author', to='api.author')),
                ('favorite_characters', models.ManyToManyField(blank=True, null=True, related_name='favorite_character', to='api.character')),
                ('favorite_illustrators', models.ManyToManyField(blank=True, null=True, related_name='favorite_illustrator', to='api.illustrator')),
                ('favorite_publishers', models.ManyToManyField(blank=True, null=True, related_name='favorite_publisher', to='api.publisher')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
