# Generated by Django 4.1 on 2022-11-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicbook',
            name='author',
        ),
        migrations.AddField(
            model_name='comicbook',
            name='authors',
            field=models.ManyToManyField(to='api.author'),
        ),
        migrations.AddField(
            model_name='comicbook',
            name='cover',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
