# Generated by Django 4.1 on 2022-11-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_comicbook_author_remove_comicbook_illustrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='cover',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
