# Generated by Django 4.1 on 2022-12-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_character_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile_picture',
            field=models.CharField(default='blank', max_length=1000),
        ),
    ]
