# Generated by Django 4.1 on 2022-12-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_character_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
