# Generated by Django 4.1 on 2022-11-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_comicbook_illustrator_comicbook_illustrators_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='first_name',
            new_name='real_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='last_name',
        ),
    ]
