# Generated by Django 4.1 on 2022-11-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_first_name_character_real_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicbook',
            name='owner',
        ),
    ]
