# Generated by Django 4.1 on 2022-11-28 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_character_alias_alter_character_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.character')),
                ('illustrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.illustrator')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_authors',
            field=models.ManyToManyField(through='api.Favorite', to='api.author'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_characters',
            field=models.ManyToManyField(through='api.Favorite', to='api.character'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_illustrators',
            field=models.ManyToManyField(through='api.Favorite', to='api.illustrator'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_publishers',
            field=models.ManyToManyField(through='api.Favorite', to='api.publisher'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
