# Generated by Django 4.1 on 2022-11-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_comicbook_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicbook',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='written_comics', to='api.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comicbook',
            name='illustrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='illustrated_comics', to='api.illustrator'),
            preserve_default=False,
        ),
    ]
